In [54]:
import os
import errno
import pickle
import xmltodict, json
import datetime
from time import time, strftime, localtime
from datetime import timedelta

import pandas as pd

In [55]:
# %load executionTimeCheck.py
from time import time, strftime, localtime
from datetime import timedelta


class checkExecution:
    def __init__(self):
        self.startTime = ''

    def secondsToStr(self, elapsed=None):
        if elapsed is None:
            return strftime("%Y-%m-%d %H:%M:%S", localtime())
        else:
            return str(timedelta(seconds=elapsed))

    def log(self, s, elapsed=None):
        line = "=" * 40
        print()
        print(line)
        print(self.secondsToStr(), '-', s)
        if elapsed:
            print("Elapsed time:", elapsed)
        print(line)
        print()

    def startLog(self):
        self.startTime = time()
        self.log("Start Program")

    def endLog(self):
        end = time()
        elapsed = end - self.startTime
        self.log("End Program", self.secondsToStr(elapsed))

In [56]:
e = checkExecution()

In [57]:
curr_path = os.getcwd()
sub_path = curr_path +"/Dataset/Information"

In [23]:
with open("/Users/tax_k/Projects/AI-DL/KB/Dataset/Information/2/7/드림스빌.txt", 'rb') as f:
    data = pickle.load(f)
print(data)

{'apt_name': '드림스빌', 'apt_jibun': '서울특별시 강동구 성내동 508-2', 'apt_area': ['76.08Am²', '78.33Bm²', '86.87m²', '89.41m²', '107.66m²'], 'subway_list': ['수도권\n5서울-5호선 강동역 601m', '수도권\n5서울-5호선 둔촌동역 916m', '수도권\n5서울-5호선 천호역 968m'], 'conv_lists': ['홈플러스익스프레스 성내점'], 'road_lists': ['-'], 'edu_lists': ['송원유치원', ' 준현유치원', ' 서울성일초등학교', ' 성내중학교'], 'medi_lists': ['병원 (2개)', ' 보건소 (1개)'], 'park_lists': ['성내근린공원'], 'etc_lists': ['강동구립성내도서관', ' 성내2동주민센터', ' 강동구청 제2청사'], 'apt_internal_info': {'총 세대수': '12세대', '총 동수': '1동', '최고층': '7층', '최저층': '7층', '총 주차대수': '12대', '세대당 주차대수': '1대', '준공년월': '2003.07', '건설사명': '대월종합건설', '난방방식(연료)': '개별(도시가스)'}}

In [58]:
e.startLog()
whole_data = []
for name in sorted(os.listdir(sub_path)):
    path = os.path.join(sub_path, name)
    if os.path.isdir(path):
        for fname in sorted(os.listdir(path)):
            fpath = os.path.join(path, fname)
            if os.path.isdir(fpath):
                for aptname in (os.listdir(fpath)):
                    only_apt_name = aptname[:-4]
                    if not aptname.startswith('.') and os.path.isfile(os.path.join(fpath, aptname)):
                        apt_name_path = os.path.join(fpath, aptname)

                        with open(apt_name_path, 'rb') as f:
                            data = pickle.load(f)
                            
                            data["gu"] = name
                            data["dong"] = fname
                            data["name"] = only_apt_name
                            if data is None:
                                print('hack')
                            else:
                                whole_data.append(data)
e.endLog()

========================================
2018-10-29 19:13:41 - Start Program
========================================


========================================
2018-10-29 19:13:46 - End Program
Elapsed time: 0:00:05.190929
========================================

In [59]:
pds_frame = pd.DataFrame(whole_data)

In [64]:
pds_frame.head()

,apt_area,apt_internal_info,apt_jibun,apt_name,conv_lists,dong,edu_lists,etc_lists,gu,medi_lists,name,park_lists,road_lists,subway_list
0,"[174.05Cm², 174.42Dm², 177.96Em², 178.91Fm², 1...","{'총 세대수': '14세대', '총 동수': '1동', '최고층': '7층', '...",서울특별시 강남구 개포동 1165,현대빌라트,[-],1,"[초원유치원, 서울포이초등학교, 국립국악고등학교]",[M극장],1,[-],현대빌라트,[달터근린공원],[-],"[수도권\n분당분당선 구룡역 75m, 수도권\n분당분당선 개포동역 398m]"
1,"[31.61m², 44.5m², 55.76Bm², 56.2m², 63.05m²]","{'총 세대수': '1,970세대', '총 동수': '30동', '최고층': '5층...",서울특별시 강남구 개포동 656,개포시영,[홈플러스익스프레스 개포2점],1,"[서울개원초등학교병설유치원, 서울구룡초등학교, 서울포이초등학교, 국립국악고등학교]","[개포1동주민센터, 개포4동주민센터]",1,[-],개포시영,[달터근린공원],"[경부고속도로 양재ic 5분, 양재대로 5분, 강남대로 5분, 남부순환로 5분]",[수도권\n분당분당선 구룡역 852m]
2,"[99.17m², 158.67m², 195.04m²]","{'총 세대수': '270세대', '총 동수': '3동', '최고층': '15층',...",서울특별시 강남구 개포동 649,경남(2차),"[롯데슈퍼 프리미엄도곡점, 홈플러스익스프레스 개포2점]",1,"[서울개일초등학교, 구룡중학교, 개포고등학교]",[개포1동주민센터],1,[-],경남(2차),"[개포근린공원, 늘벗공원, 달터근린공원, 양재천]","[양재대로 5분, 남부순환로 5분]","[수도권\n분당분당선 구룡역 447m, 수도권\n3서울-3호선 도곡역 819m]"
3,"[79.61Am², 80.06Bm², 80.42Cm², 80.43Dm², 84.67...","{'총 세대수': '10세대', '총 동수': '1동', '최고층': '5층', '...",서울특별시 강남구 개포동 1164-30,뉴현대파크빌,[-],1,"[서울포이초등학교, 국립국악고등학교]",[M극장],1,[-],뉴현대파크빌,[달터근린공원],[-],"[수도권\n분당분당선 구룡역 447m, 수도권\n3서울-3호선 도곡역 819m]"
4,"[65.21Am², 67.4Bm², 113.46Am², 114.03Bm², 154....","{'총 세대수': '15세대', '총 동수': '1동', '최고층': '6층', '...",서울특별시 강남구 개포동 1260-11,우찬현대(101),[롯데마켓999 개포4동점],1,"[초원유치원, 서울구룡초등학교, 국립국악고등학교]",[개포4동주민센터],1,[-],우찬현대(101),"[달터근린공원, 양재천]",[-],"[수도권\n분당분당선 구룡역 214m, 수도권\n3서울-3호선 도곡역 666m]"

In [61]:
print(len(whole_data))

7977

In [62]:
final_data_path = sub_path+'/whole_apt_info.txt'

In [67]:
with open(final_data_path, 'wb') as f:
    pickle.dump(pds_frame, f)

### open info_data

In [68]:
with open(final_data_path, 'rb') as f:
    info_data = pickle.load(f)

In [192]:
info_data[:1000]["apt_internal_info"][17]

{'총 세대수': '232세대',
 '총 동수': '2동',
 '최고층': '15층',
 '최저층': '12층',
 '총 주차대수': '311대',
 '세대당 주차대수': '1.34대',
 '준공년월': '1991.01',
 '건설사명': '우성건설',
 '난방방식(연료)': '지역(열병합)'}

KeyError: 17

In [198]:
info_data.loc[:][info_data['apt_name'] == '세종']

,apt_area,apt_internal_info,apt_jibun,apt_name,conv_lists,dong,edu_lists,etc_lists,gu,medi_lists,name,park_lists,road_lists,subway_list
5484,"[92.62m², 103.93m², 105.62m², 158.7m²]","{'총 세대수': '72세대', '총 동수': '1동', '최고층': '10층', ...",서울특별시 종로구 당주동 100,세종,[홈플러스익스프레스 광화문점],19,"[서울덕수초등학교병설유치원, 세종유치원, 서울덕수초등학교]","[경희궁미술관, 성곡미술관, 일민미술관, 세종센터미술관, 한국금융사박물관, ...",23,[-],세종,"[경복궁, 경희궁공원, 광화문광장, 광화문시민열린마당, 덕수궁, 세종로공원...",[-],"[수도권\n5서울-5호선 광화문역 166m, 수도권\n3서울-3호선 경복궁역 617..."
5539,"[171.88m², 187.83m², 195.61m², 199.94m², 207.2...","{'총 세대수': '9세대', '총 동수': '1동', '최고층': '6층', '최...",서울특별시 종로구 옥인동 56,세종,[-],45,"[배화여자대학교 부속 배화유치원, 옥인유치원, 서울청운초등학교, 배화여자고등학...","[통인어린이작은도서관, 박노수미술관, 청운효자동주민센터, 청와대사랑채, 경복...",23,[보건소 (1개)],세종,[무궁화동산],[-],[수도권\n1서울-1호선 종로5가역 291m]

In [113]:
len(info_data.loc[:][info_data['apt_jibun'].str.contains("강동구 강일동")])

12

### open deal_data

In [70]:
with open('w_pandas_data_frame.txt', 'rb') as f:
    deal_data = pickle.load(f)

In [73]:
deal_data.tail()

,deal_price,build_y,deal_year,law_code,apt_name,deal_month,deal_day,area,ji_bun,loc_code,current_floor
1013445,"35,000",2006,2018,천호동,부강,10,21~31,84.99,317-31,11740,2
1013446,"67,800",2009,2018,강일동,강일리버파크10단지,10,1~10,84.83,695,11740,6
1013447,"84,800",2009,2018,강일동,강일리버파크10단지,10,1~10,114.81,695,11740,10
1013448,"72,000",2009,2018,강일동,강일리버파크10단지,10,1~10,84.53,695,11740,7
1013449,"75,000",2009,2018,강일동,강일리버파크6단지,10,11~20,84.74,684,11740,13

In [85]:
deal_data.loc[:][contains_word(, deal_data['apt_name'])]

Empty DataFrame
Columns: [deal_price, build_y, deal_year, law_code, apt_name, deal_month, deal_day, area, ji_bun, loc_code, current_floor]
Index: []

### unique deal_apt_name

In [95]:
len(deal_data["apt_name"].unique()) # UNIQUE GET

ValueError: operands could not be broadcast together with shapes (7115,) (6270,)

In [88]:
len(deal_data["ji_bun"].unique()) # UNIQUE GET

6270

In [ ]:
deal_data.drop_duplicates(['apt_name', 'ji_bun'])

In [132]:
deal_data['loc_code'] = deal_data['loc_code'].astype('int64')

deal_data['deal_price'] = deal_data['deal_price'].str.replace(',', '')

In [133]:
deal_data['deal_price'] = deal_data['deal_price'].astype('int64')

In [100]:
def contains_word(w, s):
    return (' ' + w + ' ') in (' ' + s + ' ')

In [152]:

deal_data.loc[:][deal_data['law_code'].str.contains("신림")]

,deal_price,build_y,deal_year,law_code,apt_name,deal_month,deal_day,area,ji_bun,loc_code,current_floor
3612,15100,1996,2006,신림동,LIG 대학마을,1,1~10,58.9,1703-1,11620,6
3613,16500,1993,2006,신림동,신림현대,1,1~10,59.85,1694,11620,13
3614,23800,1993,2006,신림동,신림현대,1,1~10,82.2,1694,11620,10
3615,40000,2005,2006,신림동,청암두산위브센티움,1,1~10,98.31,86-3,11620,15
3616,15400,2000,2006,신림동,삼성산주공(주공3단지),1,1~10,58.55,1714,11620,1
3617,28800,2000,2006,신림동,삼성산주공(주공3단지),1,1~10,113.31,1714,11620,2
3618,10500,1993,2006,신림동,신림현대,1,1~10,34.86,1694,11620,13
3619,5500,2000,2006,신림동,태양,1,11~20,48.99,1563-2,11620,6
3620,18900,1993,2006,신림동,국제산장,1,11~20,84.15,1693,11620,5
3621,17400,1993,2006,신림동,신림현대,1,11~20,59.85,1694,11620,3
3622,18500,1993,2006,신림동,국제산장,1,11~20,84.15,1693,11620,14
3623,20800,1993,2006,신림동,국제산장,1,11~20,84.15,1693,11620,6
3624,17500,1993,2006,신림동,신림현대,1,11~20,59.85,1694,11620,9
3625,25500,2000,2006,신림동,청광,1,11~20,84.8,1716,11620,10
3626,18500,1993,2006,신림동,국제산장,1,11~20,84.15,1693,11620,11
3627,13300,1988,2006,신림동,건영2,1,11~20,59.76,721-2,11620,2
3628,10500,1993,2006,신림동,신림현대,1,11~20,34.86,1694,11620,14
3629,24700,2000,2006,신림동,삼성산주공(주공3단지),1,11~20,83.21,1714,11620,15
3630,19500,1997,2006,신림동,건영4,1,11~20,84.89,1702-1,11620,2
3631,27000,1993,2006,신림동,신림현대,1,11~20,82.2,1694,11620,5
3632,17400,1993,2006,신림동,신림현대,1,11~20,59.85,1694,11620,6
3633,63500,2005,2006,신림동,신림푸르지오,1,11~20,138.74,1730,11620,22
3634,13500,1999,2006,신림동,초원,1,11~20,59.93,1712,11620,16
3635,17000,2000,2006,신림동,삼성산주공(주공3단지),1,11~20,58.55,1714,11620,3
3636,25100,2003,2006,신림동,임광관악파크,1,11~20,84.77,1727,11620,4
3637,16500,2001,2006,신림동,한라타운아파트,1,11~20,68.339,763,11620,15
3638,17500,1993,2006,신림동,신림현대,1,11~20,59.85,1694,11620,9
3639,16500,2003,2006,신림동,임광관악파크,1,21~31,59.6,1727,11620,1
3640,17250,1996,2006,신림동,LIG 대학마을,1,21~31,69.17,1703-1,11620,1
3641,9400,1988,2006,신림동,건영2,1,21~31,43.92,721-2,11620,3
...,...,...,...,...,...,...,...,...,...,...,...
1011885,42000,1974,2018,신림동,강남,9,11~20,42.35,1644,11620,3
1011886,34500,1988,2018,신림동,건영2,9,11~20,73.48,721-2,11620,5
1011887,57000,2008,2018,신림동,관악산휴먼시아 2단지,9,11~20,84.96,1735,11620,11
1011888,31000,1995,2018,신림동,주공1,9,11~20,59.5,1704-1,11620,13
1011889,12900,2013,2018,신림동,프라비다트라움,9,11~20,14.06,1433-55,11620,8
1011890,48000,2006,2018,신림동,신림동부센트레빌,9,11~20,59.99,1734,11620,5
1011891,41700,1974,2018,신림동,강남,9,21~30,42.35,1644,11620,5
1011892,31500,1993,2018,신림동,신림현대,9,21~30,34.86,1694,11620,4
1011893,65000,2008,2018,신림동,관악산휴먼시아 2단지,9,21~30,114.7,1735,11620,4
1011894,42500,2000,2018,신림동,삼성산주공(주공3단지),9,21~30,83.21,1714,11620,14
1011895,52000,1997,2018,신림동,건영4,9,21~30,84.89,1702-1,11620,10
1011896,39500,1998,2018,신림동,금호2,9,21~30,59.96,1706,11620,11
1011897,49000,2008,2018,신림동,관악산휴먼시아 2단지,9,21~30,84.97,1735,11620,5
1011898,57000,2008,2018,신림동,관악산휴먼시아 2단지,9,21~30,84.97,1735,11620,20
1011899,30200,1993,2018,신림동,국제산장,9,21~30,59.94,1693,11620,4
1011900,38500,1997,2018,신림동,금호(1차),9,21~30,84.96,1705,11620,5
1013331,46900,2000,2018,신림동,청광,10,1~10,84.8,1716,11620,7
1013332,47000,2008,2018,신림동,관악산휴먼시아 2단지,10,1~10,59.96,1735,11620,12
1013333,57700,2008,2018,신림동,관악산휴먼시아 2단지,10,1~10,84.97,1735,11620,15
1013334,28900,1997,2018,신림동,금호(1차),10,1~10,59.4,1705,11620,1
1013335,54000,2008,2018,신림동,관악산휴먼시아 2단지,10,1~10,114.7,1735,11620,13
1013336,34500,2000,2018,신림동,삼성산주공(주공3단지),10,1~10,58.55,1714,11620,24
1013337,51500,2008,2018,신림동,관악산휴먼시아 2단지,10,1~10,84.97,1735,11620,7
1013338,44500,2016,2018,신림동,래디앙아파트,10,1~10,63.19,244-21,11620,6
1013339,40000,1974,2018,신림동,강남,10,1~10,46.72,1644,11620,2
1013340,32200,1993,2018,신림동,신림현대,10,11~20,34.86,1694,11620,10
1013341,35000,1998,2018,신림동,쌍용,10,11~20,59.26,1686,11620,7
1013342,46800,1984,2018,신림동,건영1,10,11~20,60.27,746-43,11620,8
1013343,45000,1984,2018,신림동,건영1,10,11~20,60.27,746-43,11620,6
1013344,55000,1984,2018,신림동,건영1,10,11~20,74.22,746-43,11620,12

In [200]:
deal_data.loc[:][deal_data['apt_name'] == '세종']

,deal_price,build_y,deal_year,law_code,apt_name,deal_month,deal_day,area,ji_bun,loc_code,current_floor
0,29500,1983,2006,당주동,세종,1,11~20,93.4,100,11110,6
23048,80000,1982,2006,서초동,세종,3,1~10,104.07,1310-3,11650,7
26000,28000,1983,2006,당주동,세종,4,21~30,104.73,100,11110,3
42472,95000,1982,2006,서초동,세종,5,1~10,104.07,1310-3,11650,2
61531,64560,1983,2006,당주동,세종,9,21~30,156.74,100,11110,9
91436,100000,1982,2006,서초동,세종,10,21~31,104.07,1310-3,11650,11
95582,17000,1983,2006,당주동,세종,11,1~10,91.68,100,11110,4
107040,15400,2002,2006,시흥동,세종,11,11~20,85.8,797-2,11545,4
120802,43200,1983,2007,당주동,세종,1,21~31,105.07,100,11110,7
133232,15000,2002,2007,시흥동,세종,3,11~20,67.29,797-2,11545,6
142472,44000,1983,2007,당주동,세종,6,21~30,104.73,100,11110,4
184164,22000,2002,2008,시흥동,세종,1,21~31,85.8,797-2,11545,5
200362,22800,2002,2008,시흥동,세종,3,1~10,85.8,797-2,11545,2
209610,24000,2002,2008,시흥동,세종,4,21~30,75.96,797-2,11545,5
255649,22500,2002,2009,시흥동,세종,4,1~10,75.96,797-2,11545,5
266522,45000,1983,2009,당주동,세종,6,11~20,102.89,100,11110,4
292890,47000,1983,2009,당주동,세종,9,11~20,105.07,100,11110,7
306914,74200,1983,2009,당주동,세종,12,21~31,156.74,100,11110,8
319504,41300,1983,2010,당주동,세종,3,11~20,93.4,100,11110,6
323483,47500,1983,2010,당주동,세종,4,11~20,104.73,100,11110,5
323484,46500,1983,2010,당주동,세종,4,21~30,104.73,100,11110,2
362501,41000,1983,2011,당주동,세종,2,1~10,91.46,100,11110,10
389823,40000,1983,2011,당주동,세종,8,11~20,104.73,100,11110,3
402741,50000,1983,2011,당주동,세종,11,21~30,104.73,100,11110,2
427678,42000,1983,2012,당주동,세종,6,1~10,91.68,100,11110,4
434626,50000,1983,2012,당주동,세종,9,1~10,104.73,100,11110,2
447278,75000,1983,2012,당주동,세종,12,1~10,156.74,100,11110,9
447279,42000,1983,2012,당주동,세종,12,21~31,104.73,100,11110,4
472227,51700,1983,2013,당주동,세종,5,21~31,104.73,100,11110,5
478578,54200,1983,2013,당주동,세종,6,11~20,105.07,100,11110,7
492337,53000,1983,2013,당주동,세종,9,21~30,104.73,100,11110,4
535313,72000,1983,2014,당주동,세종,3,11~20,156.74,100,11110,10
596529,14000,2002,2014,시흥동,세종,11,21~30,48.42,797-2,11545,6
598453,47000,1983,2014,당주동,세종,12,1~10,91.46,100,11110,10
647527,19000,2002,2015,시흥동,세종,4,1~10,67.29,797-2,11545,6
679922,20000,2002,2015,시흥동,세종,7,11~20,67.29,797-2,11545,6
692288,57000,1983,2015,당주동,세종,9,21~30,104.5,100,11110,8
754545,43000,1983,2016,당주동,세종,5,11~20,91.68,100,11110,2
778689,65000,1983,2016,당주동,세종,7,1~10,105.64,100,11110,6
801551,43500,1983,2016,당주동,세종,9,21~30,91.68,100,11110,2
835041,61500,1983,2017,당주동,세종,1,1~10,104.5,100,11110,9
862506,64800,1983,2017,당주동,세종,5,1~10,104.73,100,11110,4
871314,27000,2002,2017,시흥동,세종,5,11~20,85.8,797-2,11545,2
877486,65500,1983,2017,당주동,세종,6,21~30,104.5,100,11110,10
910411,64800,1983,2017,당주동,세종,9,11~20,104.5,100,11110,10
928545,24500,2002,2017,시흥동,세종,11,21~30,75.96,797-2,11545,5
940289,66000,1983,2018,당주동,세종,1,11~20,104.73,100,11110,3
962037,62000,1983,2018,당주동,세종,3,1~10,91.46,100,11110,9
975924,66900,1983,2018,당주동,세종,5,11~20,104.73,100,11110,4

In [148]:
df = deal_data.loc[:][deal_data['apt_name'] == '강일리버파크10단지']
df.shape
df.columns.values

array(['deal_price', 'build_y', 'deal_year', 'law_code', 'apt_name',
       'deal_month', 'deal_day', 'area', 'ji_bun', 'loc_code',
       'current_floor'], dtype=object)

In [137]:
import matplotlib.pyplot as plt
import matplotlib.colors

In [ ]:
# paired_colors = plt.cm.Paired(range(len(train_class)))

In [ ]:
fig, ax = plt.subplots()
for key, grp in deal_data.groupby(['loc_code']):
    ax = grp.plot(ax=ax, kind='line', x='deal_year', y='deal_price', c=key, label=key)
plt.legend(loc='best')
plt.show()

In [ ]:
ax = plt.gca()

deal_data.plot(kind='line',x=deal_data["deal_year"],y=deal_data["deal_price"],ax=ax)

plt.show()

### Pandas Merge Test

In [167]:
merged = pd.merge(deal_data, info_data, on="apt_name", how="inner")

In [197]:
merged.head()

,deal_price,build_y,deal_year,law_code,apt_name,deal_month,deal_day,area,ji_bun,loc_code,...,conv_lists,dong,edu_lists,etc_lists,gu,medi_lists,name,park_lists,road_lists,subway_list
0,29500,1983,2006,당주동,세종,1,11~20,93.4,100,11110,...,[홈플러스익스프레스 광화문점],19,"[서울덕수초등학교병설유치원, 세종유치원, 서울덕수초등학교]","[경희궁미술관, 성곡미술관, 일민미술관, 세종센터미술관, 한국금융사박물관, ...",23,[-],세종,"[경복궁, 경희궁공원, 광화문광장, 광화문시민열린마당, 덕수궁, 세종로공원...",[-],"[수도권\n5서울-5호선 광화문역 166m, 수도권\n3서울-3호선 경복궁역 617..."
1,29500,1983,2006,당주동,세종,1,11~20,93.4,100,11110,...,[-],45,"[배화여자대학교 부속 배화유치원, 옥인유치원, 서울청운초등학교, 배화여자고등학...","[통인어린이작은도서관, 박노수미술관, 청운효자동주민센터, 청와대사랑채, 경복...",23,[보건소 (1개)],세종,[무궁화동산],[-],[수도권\n1서울-1호선 종로5가역 291m]
2,80000,1982,2006,서초동,세종,3,1~10,104.07,1310-3,11650,...,[홈플러스익스프레스 광화문점],19,"[서울덕수초등학교병설유치원, 세종유치원, 서울덕수초등학교]","[경희궁미술관, 성곡미술관, 일민미술관, 세종센터미술관, 한국금융사박물관, ...",23,[-],세종,"[경복궁, 경희궁공원, 광화문광장, 광화문시민열린마당, 덕수궁, 세종로공원...",[-],"[수도권\n5서울-5호선 광화문역 166m, 수도권\n3서울-3호선 경복궁역 617..."
3,80000,1982,2006,서초동,세종,3,1~10,104.07,1310-3,11650,...,[-],45,"[배화여자대학교 부속 배화유치원, 옥인유치원, 서울청운초등학교, 배화여자고등학...","[통인어린이작은도서관, 박노수미술관, 청운효자동주민센터, 청와대사랑채, 경복...",23,[보건소 (1개)],세종,[무궁화동산],[-],[수도권\n1서울-1호선 종로5가역 291m]
4,28000,1983,2006,당주동,세종,4,21~30,104.73,100,11110,...,[홈플러스익스프레스 광화문점],19,"[서울덕수초등학교병설유치원, 세종유치원, 서울덕수초등학교]","[경희궁미술관, 성곡미술관, 일민미술관, 세종센터미술관, 한국금융사박물관, ...",23,[-],세종,"[경복궁, 경희궁공원, 광화문광장, 광화문시민열린마당, 덕수궁, 세종로공원...",[-],"[수도권\n5서울-5호선 광화문역 166m, 수도권\n3서울-3호선 경복궁역 617..."

In [174]:
merged.columns

Index(['deal_price', 'build_y', 'deal_year', 'law_code', 'apt_name',
       'deal_month', 'deal_day', 'area', 'ji_bun', 'loc_code', 'current_floor',
       'apt_area', 'apt_internal_info', 'apt_jibun', 'conv_lists', 'dong',
       'edu_lists', 'etc_lists', 'gu', 'medi_lists', 'name', 'park_lists',
       'road_lists', 'subway_list'],
      dtype='object')

In [181]:
# merged.loc[merged.isnull()]

merged.isnull().values.any()

False

In [187]:
merged.loc[:][merged['law_code'].str.contains("신림")]

print(type(merged.columns.values))

<class 'numpy.ndarray'>

In [183]:
type(merged)merged.columns.values

pandas.core.frame.DataFrame

In [188]:
merged.drop_duplicates(subset=merged.columns.values, keep=False)

TypeError: unhashable type: 'list'